routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });


Auth::routes();
Route::group(['middleware' => ['auth']], function() {
  Route::get('/', 'KriteriaController@index');
  Route::get('/result', 'ResultController@index')->name('result');
  Route::get('/gAhpKri', 'ResultController@gAhpKri')->name('gAhpKri');
  Route::get('/gAhpSub', 'ResultController@gAhpSub')->name('gAhpSub');
  Route::get('/gAhpPem', 'ResultController@gAhpPem')->name('gAhpPem');
  Route::get('/gFuzKri', 'ResultController@gFuzKri')->name('gFuzKri');
  Route::get('/gFuzSub', 'ResultController@gFuzSub')->name('gFuzSub');
  Route::get('/gFuzPem', 'ResultController@gFuzPem')->name('gFuzPem');

  Route::resource('kriterias', 'KriteriaController');

  Route::resource('subKriterias', 'SubKriteriaController');

  Route::resource('experts', 'ExpertController');

  Route::resource('kriteriaKriterias', 'KriteriaKriteriaController');

  Route::get('/kriteriaKriterias/create/{id}', 'KriteriaKriteriaController@create')->name('CreateKriteriaKriteria');
  Route::get('/subKriterias/create/{id}', 'SubKriteriaController@create')->name('CreateSubKriteria');

  Route::get('/subKriteriaSubKriterias/create/{id}', 'SubKriteriaSubKriteriaController@create')->name('CreateSubKriteriaSubKriteria');
  Route::resource('subKriteriaSubKriterias', 'SubKriteriaSubKriteriaController');
  Route::resource('kriterias.SubKriterias', 'SubKriteriaController');
  Route::get('/subKriterias/kriterias/{id}', 'SubKriteriaSubKriteriaController@kriteria')->name('showKriterias');


  Route::resource('pemasoks', 'PemasokController');

  Route::resource('experts.pemasokSubs', 'PemasokSubController');
  Route::resource('pemasokSubs', 'PemasokSubController');
  Route::delete('/destroyAllByExpertId/{expert_id}', ['uses' => 'KriteriaKriteriaController@destroyAllByExpertId', 'as' => 'dKri']);
  Route::delete('/destroyAllSubByKriteriaId/{kriteria_id}', ['uses'=>'SubKriteriaSubKriteriaController@destroyAllByKriteriaId', 'as' => 'dSub']);
  Route::delete('/destroyAllPSubsByExpertId/{expert_id}', ['uses'=>'PemasokSubController@destroyAllByExpertId', 'as'=>'dPSub']);


});

app/Models/PemasokSub.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class PemasokSub
 * @package App\Models
 * @version October 17, 2017, 12:19 am UTC
 *
 * @property integer pemasok1_id
 * @property float nilai
 * @property integer pemasok2_id
 * @property integer kriteria_id
 */
class PemasokSub extends Model
{
    use SoftDeletes;

    public $table = 'pemasok_subs';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'pemasok1_id',
        'nilai',
        'pemasok2_id',
        'kriteria_id',
        'expert_id',
        'sub_kriteria_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'pemasok1_id' => 'integer',
        'nilai' => 'float',
        'pemasok2_id' => 'integer',
        'kriteria_id' => 'integer',
        'expert_id' => 'integer',
        'sub_kriteria_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'pemasok1_id' => 'required',
        'nilai' => 'required',
        'pemasok2_id' => 'required',
        'kriteria_id' => 'required',
        'expert_id' => 'required',
        'sub_kriteria_id' => 'required'
    ];

    public function kriteria()
    {
        return $this->belongsTo('App\Models\Kriteria', 'kriteria_id', 'id');
    }

    public function expert()
    {
        return $this->belongsTo('App\Models\Expert', 'expert_id', 'id');
    }

    public function subKriteria(){
      return $this->belongsTo('App\Models\SubKriteria', 'sub_kriteria_id', 'id');
    }
}

app/Http/Controllers/PemasokSubController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePemasokSubRequest;
use App\Http\Requests\UpdatePemasokSubRequest;
use App\Repositories\PemasokSubRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\SubKriteria;
use App\Models\PemasokSub;
use App\Models\Kriteria;
use App\Models\Pemasok;
use App\Models\Expert;

class PemasokSubController extends AppBaseController
{
    /** @var  PemasokSubRepository */
    private $pemasokSubRepository;

    public function __construct(PemasokSubRepository $pemasokSubRepo)
    {
        $this->pemasokSubRepository = $pemasokSubRepo;
    }

    /**
     * Display a listing of the PemasokSub.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->pemasokSubRepository->pushCriteria(new RequestCriteria($request));
        $pemasokSubs = $this->pemasokSubRepository->all();
        $kriterias = Kriteria::pluck('nama_kriteria', 'id');
        $subKriterias = SubKriteria::pluck('nama_sub_kriteria', 'id');
        $experts = Expert::pluck('nama', 'id');

        return view('pemasok_subs.index')
            ->with('pemasokSubs', $pemasokSubs)
            ->with('kriterias', $kriterias)
            ->with('subKriterias', $subKriterias);
    }

    /**
     * Show the form for creating a new PemasokSub.
     *
     * @return Response
     */
    public function create($id)
    {
      $expert = Expert::find($id);
      $experts = Expert::all();
      $hit = 0;
      foreach ($experts as $key => $value) {
        $hit++;
        if($value->id == $id){
          break;
        }
      }
      // dd($hit);
      $ps = PemasokSub::where('expert_id','=',$id)->orderBy('kriteria_id','ASC')->orderBy('sub_kriteria_id','ASC')->orderBy('pemasok1_id','ASC')->get();
      $pemasoks = Pemasok::all();
      $subKriterias = SubKriteria::all();
      //dd($kriterias);
      $p = Pemasok::all()->pluck('nama_pemasok', 'id');
      //dd($k);
      $pemasok1 = null;
      $kriterias = Kriteria::all();
      $selectedKri = null;
      foreach ($kriterias as $kk => $vk) {
        $ck = PemasokSub::all()->where('kriteria_id','=', $vk->id)->count();
        $csub = SubKriteria::all()->where('kriteria_id','=',$vk->id)->count();
          // dd($csub);
        if($ck < countTable($pemasoks->count())*$csub* Expert::all()->count()){
          $selectedKri = $vk;
          break;
        }
      }
      $selectedSub = null;
      $hms = $subKriterias->where('kriteria_id','=',$selectedKri->id);
      // dd($hms);
      foreach ($hms as $key => $value) {
        $cSub = PemasokSub::all()->where('sub_kriteria_id', '=', $value->id)->where('expert_id','=',$id)->count();
        // dd($cSub);
        if($cSub  <= countTable($pemasoks->count()) * $hit){
          $selectedSub = $value;
          break;
        }
      }
      // dd($selectedSub);
      $pemasokSubs = PemasokSub::all()->where("expert_id",'=', $id);
      $pemasok2 = null;
      $ketemu = false;
      $full = countTable($pemasoks->count()) == $pemasokSubs->count() ? true : false;
      foreach ($pemasoks as $p1) {
        if($selectedKri==null || $selectedSub==null) break;
        $count = $pemasokSubs->where('pemasok1_id', '=', $p1->id)->where('kriteria_id', '=', $selectedKri->id)->where('sub_kriteria_id', '=', $selectedSub->id)->count() +
                  $pemasokSubs->where('pemasok2_id', '=', $p1->id)->where('kriteria_id', '=', $selectedKri->id)->where('sub_kriteria_id', '=', $selectedSub->id)->count();
        $countKri = $subKriterias->where('kriteria_id','=', $selectedKri->id);
                // var_dump($countKri->count());
        // dd($count);
        // if($count < $kriterias->count()*$countKri->count()){
          // dd($count);
          foreach ($pemasoks as $p2) {
              if($p1->id != $p2->id){
                // dd($selectedSub);
                $ada1 = $pemasokSubs->where('pemasok1_id', '=', "$p1->id")->where('pemasok2_id', '=', "$p2->id")->where('sub_kriteria_id', '=', $selectedSub->id)->count();
                $ada2 = $pemasokSubs->where('pemasok1_id', '=', "$p2->id")->where('pemasok2_id', '=', "$p1->id")->where('sub_kriteria_id', '=', $selectedSub->id)->count();
                if($ada1 == 0 && $ada2 == 0 ){
                  $pemasok1 = $p1;
                  $pemasok2 = $p2;
                  $ketemu = true;
                  break;
                }
              }
          }
        // }
        if($ketemu==true) break;
      }
      // dd($count);
      // dd($id);
      return view('pemasok_subs.create')->with('expert', $expert)
                  ->with('pemasok1', $pemasok1)->with('pemasok2', $pemasok2)
                  ->with('full', $full)->with('pemasokSubs', $pemasokSubs)
                  ->with('kriterias', $kriterias)->with('pemasoks', $pemasoks)
                  ->with('subKriteria', $selectedSub)->with('selectedSub', $selectedSub)
                  ->with('selectedKri', $selectedKri)->with('ps', $ps)
                  ->with('p', $p);
    }


    /**
     * Store a newly created PemasokSub in storage.
     *
     * @param CreatePemasokSubRequest $request
     *
     * @return Response
     */
    public function store(CreatePemasokSubRequest $request)
    {
        $input = $request->all();
        //dd($input);
        $pemasokSub = $this->pemasokSubRepository->create($input);

        Flash::success('Pemasok Sub saved successfully.');

        return \App::make('redirect')->back();
    }

    /**
     * Display the specified PemasokSub.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $pemasokSub = $this->pemasokSubRepository->findWithoutFail($id);

        if (empty($pemasokSub)) {
            Flash::error('Pemasok Sub not found');

            return redirect(route('pemasokSubs.index'));
        }
        $pemasok1 = Pemasok::find($pemasokSub->pemasok1_id);
        $pemasok2 = Pemasok::find($pemasokSub->pemasok2_id);
        return view('pemasok_subs.show')->with('pemasokSub', $pemasokSub)
                  ->with('pemasok1',$pemasok1)
                  ->with('pemasok2',$pemasok2);
    }

    /**
     * Show the form for editing the specified PemasokSub.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $pemasokSub = $this->pemasokSubRepository->findWithoutFail($id);

        if (empty($pemasokSub)) {
            Flash::error('Pemasok Sub not found');

            return redirect(route('pemasokSubs.index'));
        }
        $pemasok1 = Pemasok::find($pemasokSub->pemasok1_id);
        $pemasok2 = Pemasok::find($pemasokSub->pemasok2_id);
        $subKriteria = SubKriteria::find($pemasokSub->sub_kriteria_id);
        $expert = Expert::find($pemasokSub->expert_id);
        return view('pemasok_subs.edit')->with('pemasokSub', $pemasokSub)
                ->with('pemasok1',$pemasok1)
                ->with('pemasok2',$pemasok2)
                ->with('subKriteria', $subKriteria)
                ->with('expert', $expert);
    }

    /**
     * Update the specified PemasokSub in storage.
     *
     * @param  int              $id
     * @param UpdatePemasokSubRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePemasokSubRequest $request)
    {
        $pemasokSub = $this->pemasokSubRepository->findWithoutFail($id);

        if (empty($pemasokSub)) {
            Flash::error('Pemasok Sub not found');

            return redirect(route('pemasokSubs.index'));
        }
        $expert_id = $pemasokSub->expert_id;
        $pemasokSub = $this->pemasokSubRepository->update($request->all(), $id);

        Flash::success('Pemasok Sub updated successfully.');

        return redirect(route('experts.pemasokSubs.create', [$id=>$expert_id]));
    }

    public function destroyAllByExpertId($expert_id){
        $pemasokSub = PemasokSub::where('expert_id','=',$expert_id);

      if (empty(count($pemasokSub->get()))) {
          Flash::error('Pemasok Sub not found');

          return \App::make('redirect')->back();
      }

      $pemasokSub->delete();

      Flash::success('Pemasok Sub deleted successfully.');

      return \App::make('redirect')->back();
    }
}

resources/views/pemasok_subs/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
      @if($selectedKri != null && $selectedSub !=null)
        <h1>
            Input perbandingan untuk <strong>{!! $selectedSub->nama_sub_kriteria !!} ({!! $selectedKri->nama_kriteria !!})</strong> oleh <strong>{!! $expert->nama !!}</strong>
        </h1>
      @endif
      <h1 class="pull-right">
        {!! Form::open(['route' => ['dPSub', $expert->id], 'method' => 'delete']) !!}
        {!! Form::button('Delete All', ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
        {!! Form::close() !!}
      </h1>
    </section>
    <div class="content">
      <div class="clearfix"></div>

      @include('flash::message')

      <div class="clearfix"></div>
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                  @if($pemasok1 != null && $pemasok2 != null)
                    {!! Form::open(['route' => 'pemasokSubs.store']) !!}

                        @include('pemasok_subs.fields')

                    {!! Form::close() !!}
                  @else
                    <strong>Perbandingan sudah terpenuhi!</strong>
                  @endif
                </div>
            </div>

            <div class="clearfix"></div>
            <div class="box box-primary">
                <div class="box-body">
                        @include('pemasok_subs.table2')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pemasok_subs/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Pemasok Sub
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($pemasokSub, ['route' => ['pemasokSubs.update', $pemasokSub->id], 'method' => 'patch']) !!}

                        @include('pemasok_subs.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/pemasok_subs/fields.blade.php
<!-- Pemasok1 Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('pemasok1_id', 'Pemasok 2:') !!}
    {!! Form::text('', $pemasok1->nama_pemasok, ['class' => 'form-control', 'disabled']) !!}
    {!! Form::hidden('pemasok1_id', $pemasok1->id) !!}
</div>

<!-- Nilai Field -->
<div class="form-group col-sm-3">
    {!! Form::label('nilai', 'Nilai:') !!}
    {!! Form::text('nilai', null, ['class' => 'form-control', 'autofocus']) !!}
</div>

<!-- Pemasok2 Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('pemasok2_id', 'Pemasok 2:') !!}
    {!! Form::text('', $pemasok2->nama_pemasok, ['class' => 'form-control', 'disabled']) !!}
    {!! Form::hidden('pemasok2_id', $pemasok2->id) !!}
</div>

    {!! Form::hidden('kriteria_id', $subKriteria->kriteria_id) !!}

    {!! Form::hidden('expert_id', $expert->id) !!}

    {!! Form::hidden('sub_kriteria_id', $subKriteria->id)!!}

<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/pemasok_subs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Pemasok Subs</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('pemasokSubs.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('pemasok_subs.table')
            </div>
        </div>
    </div>
@endsection

resources/views/pemasok_subs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Pemasok Sub
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('pemasok_subs.show_fields')
                    <a href="{!! route('pemasokSubs.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pemasok_subs/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $pemasokSub->id !!}</p>
</div>

<!-- Pemasok1 Id Field -->
<div class="form-group">
    {!! Form::label('pemasok1_id', 'Pemasok1 Id:') !!}
    <p>{!! $pemasokSub->pemasok1_id !!}</p>
</div>

<!-- Nilai Field -->
<div class="form-group">
    {!! Form::label('nilai', 'Nilai:') !!}
    <p>{!! $pemasokSub->nilai !!}</p>
</div>

<!-- Pemasok2 Id Field -->
<div class="form-group">
    {!! Form::label('pemasok2_id', 'Pemasok2 Id:') !!}
    <p>{!! $pemasokSub->pemasok2_id !!}</p>
</div>

<!-- Kriteria Id Field -->
<div class="form-group">
    {!! Form::label('kriteria_id', 'Kriteria Id:') !!}
    <p>{!! $pemasokSub->kriteria_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $pemasokSub->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $pemasokSub->updated_at !!}</p>
</div>

resources/views/pemasok_subs/table.blade.php
<table class="table table-responsive" id="pemasokSubs-table">
    <thead>
        <tr>
            <th>Pemasok1 Id</th>
        <th>Nilai</th>
        <th>Pemasok2 Id</th>
        <th>Kriteria Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($pemasokSubs as $pemasokSub)
        <tr>
            <td>{!! $pemasokSub->pemasok1_id !!}</td>
            <td>{!! $pemasokSub->nilai !!}</td>
            <td>{!! $pemasokSub->pemasok2_id !!}</td>
            <td>{!! $pemasokSub->kriteria_id !!}</td>
            <td>
                {!! Form::open(['route' => ['pemasokSubs.destroy', $pemasokSub->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('pemasokSubs.show', [$pemasokSub->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('pemasokSubs.edit', [$pemasokSub->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/pemasok_subs/table2.blade.php
@foreach ($kriterias as $kk => $v)
  @php
    $psk = $ps->where('kriteria_id','=',$v->id);
  @endphp


  <br>
    <hr>
    <div class="clearfix"></div>
  <h4><strong>{!! $v->nama_kriteria !!}</strong></h4>
  <table class="table table-responsive" id="pemasokSubs-table">
      <thead>
          <tr>
          <th>#</th>
          <th>Pemasok1</th>
          <th>Nilai</th>
          <th>Pemasok2</th>
          <th>Sub Kriteria</th>
              <th colspan="3">Action</th>
          </tr>
      </thead>
      <tbody>
        @php
          $no = 1;
        @endphp
      @foreach($psk as $pemasokSub)
          <tr>
              <td>{!! $no++ !!}</td>
              <td>{!! $p[$pemasokSub->pemasok1_id] !!}</td>
              <td>{!! $pemasokSub->nilai !!}</td>
              <td>{!! $p[$pemasokSub->pemasok2_id] !!}</td>
              <td>{!! $pemasokSub->subKriteria->nama_sub_kriteria !!}</td>
              <td>
                  {!! Form::open(['route' => ['pemasokSubs.destroy', $pemasokSub->id], 'method' => 'delete']) !!}
                  <div class='btn-group'>
                      <a href="{!! route('pemasokSubs.edit', [$pemasokSub->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                  </div>
              </td>
          </tr>
      @endforeach
      </tbody>
  </table>
@endforeach