routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });


Auth::routes();
Route::group(['middleware' => ['auth']], function() {
  Route::get('/', 'KriteriaController@index');
  Route::get('/result', 'ResultController@index')->name('result');
  Route::get('/gAhpKri', 'ResultController@gAhpKri')->name('gAhpKri');
  Route::get('/gAhpSub', 'ResultController@gAhpSub')->name('gAhpSub');
  Route::get('/gAhpPem', 'ResultController@gAhpPem')->name('gAhpPem');
  Route::get('/gFuzKri', 'ResultController@gFuzKri')->name('gFuzKri');
  Route::get('/gFuzSub', 'ResultController@gFuzSub')->name('gFuzSub');
  Route::get('/gFuzPem', 'ResultController@gFuzPem')->name('gFuzPem');

  Route::resource('kriterias', 'KriteriaController');

  Route::resource('subKriterias', 'SubKriteriaController');

  Route::resource('experts', 'ExpertController');

  Route::resource('kriteriaKriterias', 'KriteriaKriteriaController');

  Route::get('/kriteriaKriterias/create/{id}', 'KriteriaKriteriaController@create')->name('CreateKriteriaKriteria');
  Route::get('/subKriterias/create/{id}', 'SubKriteriaController@create')->name('CreateSubKriteria');

  Route::get('/subKriteriaSubKriterias/create/{id}', 'SubKriteriaSubKriteriaController@create')->name('CreateSubKriteriaSubKriteria');
  Route::resource('subKriteriaSubKriterias', 'SubKriteriaSubKriteriaController');
  Route::resource('kriterias.SubKriterias', 'SubKriteriaController');
  Route::get('/subKriterias/kriterias/{id}', 'SubKriteriaSubKriteriaController@kriteria')->name('showKriterias');


  Route::resource('pemasoks', 'PemasokController');

  Route::resource('experts.pemasokSubs', 'PemasokSubController');
  Route::resource('pemasokSubs', 'PemasokSubController');
  Route::delete('/destroyAllByExpertId/{expert_id}', ['uses' => 'KriteriaKriteriaController@destroyAllByExpertId', 'as' => 'dKri']);
  Route::delete('/destroyAllSubByKriteriaId/{kriteria_id}', ['uses'=>'SubKriteriaSubKriteriaController@destroyAllByKriteriaId', 'as' => 'dSub']);
  Route::delete('/destroyAllPSubsByExpertId/{expert_id}', ['uses'=>'PemasokSubController@destroyAllByExpertId', 'as'=>'dPSub']);


});

app/Models/SubKriteria.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class SubKriteria
 * @package App\Models
 * @version October 13, 2017, 3:13 pm UTC
 *
 * @property integer kriteria_id
 * @property string nama_sub_kriteria
 */
class SubKriteria extends Model
{
    use SoftDeletes;

    public $table = 'sub_kriterias';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'kriteria_id',
        'nama_sub_kriteria'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'kriteria_id' => 'integer',
        'nama_sub_kriteria' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'kriteria_id' => 'required',
        'nama_sub_kriteria' => 'required'
    ];

          public function kriteria()
          {
              return $this->belongsTo('App\Models\Kriteria', 'kriteria_id', 'id');
          }

          public function expert()
          {
              return $this->belongsTo('App\Models\Expert', 'expert_id', 'id');
          }

          // public function subKriteria()
          // {
          //     return $this->hasMany('App\Models\SubKriteriaSubKriteria', 'sub_kriteria1_id', 'id');
          // }

          public function next(){
              return SubKriteria::where('id', '>', $this->id)->orderBy('id','asc')->first();

          }
          public  function previous(){
              return SubKriteria::where('id', '<', $this->id)->orderBy('id','desc')->first();

          }

}

app/Http/Controllers/SubKriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSubKriteriaRequest;
use App\Http\Requests\UpdateSubKriteriaRequest;
use App\Repositories\SubKriteriaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\Kriteria;
use App\Models\SubKriteria;
use App\Models\SubKriteriaSubKriteria;

class SubKriteriaController extends AppBaseController
{
    /** @var  SubKriteriaRepository */
    private $subKriteriaRepository;

    public function __construct(SubKriteriaRepository $subKriteriaRepo)
    {
        $this->subKriteriaRepository = $subKriteriaRepo;
    }

    /**
     * Display a listing of the SubKriteria.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->subKriteriaRepository->pushCriteria(new RequestCriteria($request));
        $subKriterias = $this->subKriteriaRepository->all();

        return view('sub_kriterias.index')
            ->with('subKriterias', $subKriterias);
    }

    /**
     * Show the form for creating a new SubKriteria.
     *
     * @return Response
     */
    public function create($id)
    {

        $kriteria = Kriteria::find($id);
        $subKriterias = SubKriteria::all()->where('kriteria_id', '=', $id);
        return view('sub_kriterias.create')->with('kriteria', $kriteria)->with('subKriterias', $subKriterias);
    }

    /**
     * Store a newly created SubKriteria in storage.
     *
     * @param CreateSubKriteriaRequest $request
     *
     * @return Response
     */
    public function store(CreateSubKriteriaRequest $request)
    {
        $input = $request->all();
        $kriteria_id = $input['kriteria_id'];

        $subKriteria = $this->subKriteriaRepository->create($input);

        Flash::success('Sub Kriteria saved successfully.');
        return redirect(route('CreateSubKriteria', ['id' => $kriteria_id]));
    }

    /**
     * Display the specified SubKriteria.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $subKriteria = $this->subKriteriaRepository->findWithoutFail($id);
        $kriteria = Kriteria::find($subKriteria->kriteria_id);
        if (empty($subKriteria)) {
            Flash::error('Sub Kriteria not found');

            return redirect(route('subKriterias.index'));
        }

        return view('sub_kriterias.show')->with('subKriteria', $subKriteria)->with('kriteria', $kriteria);
    }

    /**
     * Show the form for editing the specified SubKriteria.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $subKriteria = $this->subKriteriaRepository->findWithoutFail($id);
        $kriteria = Kriteria::find($subKriteria->kriteria_id);

        if (empty($subKriteria)) {
            Flash::error('Sub Kriteria not found');

            return redirect(route('subKriterias.index'));
        }

        return view('sub_kriterias.edit')->with('subKriteria', $subKriteria)->with('kriteria', $kriteria);
    }

    /**
     * Update the specified SubKriteria in storage.
     *
     * @param  int              $id
     * @param UpdateSubKriteriaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSubKriteriaRequest $request)
    {
        $subKriteria = $this->subKriteriaRepository->findWithoutFail($id);
        $kriteria_id = $subKriteria->kriteria_id;

        if (empty($subKriteria)) {
            Flash::error('Sub Kriteria not found');

            return redirect(route('subKriterias.index'));
        }

        $subKriteria = $this->subKriteriaRepository->update($request->all(), $id);

        Flash::success('Sub Kriteria updated successfully.');

        return redirect(route('CreateSubKriteria', ['id' => $kriteria_id]));
    }

    /**
     * Remove the specified SubKriteria from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $subKriteria = $this->subKriteriaRepository->findWithoutFail($id);

        if (empty($subKriteria)) {
            Flash::error('Sub Kriteria not found');

            return redirect(route('subKriterias.index'));
        }
        PemasokSub::where('sub_kriteria_id', '=', $id)->delete();
        SubKriteriaSubKriteria::where('sub_kriteria_id', '=', $id)->delete();
        ExpertKriteriaComparison::truncate();
        ExpertSubComparison::truncate();
        FuzzyKriteria::truncate();
        FuzzySub::truncate();
        PemasokSubFuzzyResult::truncate();
        PemasokSubResult::truncate();

        $this->subKriteriaRepository->delete($id);

        Flash::success('Sub Kriteria deleted successfully.');

        return redirect(route('subKriterias.index'));
    }
}

resources/views/sub_kriterias/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sub Kriteria Form for {!! $kriteria->nama_kriteria !!}
        </h1>
    </section>
    <div class="content">
      <div class="clearfix"></div>

      @include('flash::message')
      <h1 class="pull-right">
        {!! Form::open(['route' => ['CreateSubKriteriaSubKriteria', $kriteria->id], 'method' => 'get']) !!}
            {!! Form::button('Perbandingan Sub Kriteria', ['type' => 'submit', 'class' => 'btn btn-primary pull-right']) !!}
        {!! Form::close() !!}
         </h1>
      <div class="clearfix"></div>
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'subKriterias.store']) !!}

                        @include('sub_kriterias.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        <section class="content-header">
            <h1>
                Sub Kriteria Lists for {!! $kriteria->nama_kriteria !!}
            </h1>
        </section>
        <div class="box box-primary">
            <div class="box-body">
              @if (count($subKriterias)>0)
                <table class="table table-responsive" id="subKriterias-table">
                    <thead>
                        <tr>
                            <th>#</th>
                        <th>Nama Sub Kriteria</th>
                            <th colspan="3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @php
                      $no = 1;
                    @endphp
                    @foreach($subKriterias as $subKriteria)
                        <tr>
                            <td>{!! $no++ !!}</td>
                            <td>{!! $subKriteria->nama_sub_kriteria !!}</td>
                            <td>
                                {!! Form::open(['route' => ['subKriterias.destroy', $subKriteria->id], 'method' => 'delete']) !!}
                                <div class='btn-group'>
                                    <a href="{!! route('subKriterias.edit', [$subKriteria->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                </div>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
              @else
                  <div class="clearfix">Empty</div>
              @endif
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-sm-12">
              <a href="{!! route('kriterias.index') !!}" class="btn btn-default">Back</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
@endsection

resources/views/sub_kriterias/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sub Kriteria
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($subKriteria, ['route' => ['subKriterias.update', $subKriteria->id], 'method' => 'patch']) !!}

                        @include('sub_kriterias.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/sub_kriterias/fields.blade.php
    {!! Form::hidden('kriteria_id', $kriteria->id )!!}

<!-- Nama Sub Kriteria Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nama_sub_kriteria', 'Nama Sub Kriteria:') !!}
    {!! Form::text('nama_sub_kriteria', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/sub_kriterias/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Sub Kriterias</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('subKriterias.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('sub_kriterias.table')
            </div>
        </div>
    </div>
@endsection

resources/views/sub_kriterias/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sub Kriteria
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('sub_kriterias.show_fields')
                    <a href="{!! route('subKriterias.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sub_kriterias/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $subKriteria->id !!}</p>
</div>

<!-- Kriteria Id Field -->
<div class="form-group">
    {!! Form::label('kriteria_id', 'Kriteria Id:') !!}
    <p>{!! $subKriteria->kriteria_id !!}</p>
</div>

<!-- Nama Sub Kriteria Field -->
<div class="form-group">
    {!! Form::label('nama_sub_kriteria', 'Nama Sub Kriteria:') !!}
    <p>{!! $subKriteria->nama_sub_kriteria !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $subKriteria->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $subKriteria->updated_at !!}</p>
</div>

resources/views/sub_kriterias/table.blade.php
<table class="table table-responsive" id="subKriterias-table">
    <thead>
        <tr>
            <th>Kriteria Id</th>
        <th>Nama Sub Kriteria</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($subKriterias as $subKriteria)
        <tr>
            <td>{!! $subKriteria->kriteria_id !!}</td>
            <td>{!! $subKriteria->nama_sub_kriteria !!}</td>
            <td>
                {!! Form::open(['route' => ['subKriterias.destroy', $subKriteria->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    
                    <a href="{!! route('subKriterias.edit', [$subKriteria->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>