routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });


Auth::routes();
Route::group(['middleware' => ['auth']], function() {
  Route::get('/', 'KriteriaController@index');
  Route::get('/result', 'ResultController@index')->name('result');
  Route::get('/gAhpKri', 'ResultController@gAhpKri')->name('gAhpKri');
  Route::get('/gAhpSub', 'ResultController@gAhpSub')->name('gAhpSub');
  Route::get('/gAhpPem', 'ResultController@gAhpPem')->name('gAhpPem');
  Route::get('/gFuzKri', 'ResultController@gFuzKri')->name('gFuzKri');
  Route::get('/gFuzSub', 'ResultController@gFuzSub')->name('gFuzSub');
  Route::get('/gFuzPem', 'ResultController@gFuzPem')->name('gFuzPem');

  Route::resource('kriterias', 'KriteriaController');

  Route::resource('subKriterias', 'SubKriteriaController');

  Route::resource('experts', 'ExpertController');

  Route::resource('kriteriaKriterias', 'KriteriaKriteriaController');

  Route::get('/kriteriaKriterias/create/{id}', 'KriteriaKriteriaController@create')->name('CreateKriteriaKriteria');
  Route::get('/subKriterias/create/{id}', 'SubKriteriaController@create')->name('CreateSubKriteria');

  Route::get('/subKriteriaSubKriterias/create/{id}', 'SubKriteriaSubKriteriaController@create')->name('CreateSubKriteriaSubKriteria');
  Route::resource('subKriteriaSubKriterias', 'SubKriteriaSubKriteriaController');
  Route::resource('kriterias.SubKriterias', 'SubKriteriaController');
  Route::get('/subKriterias/kriterias/{id}', 'SubKriteriaSubKriteriaController@kriteria')->name('showKriterias');


  Route::resource('pemasoks', 'PemasokController');

  Route::resource('experts.pemasokSubs', 'PemasokSubController');
  Route::resource('pemasokSubs', 'PemasokSubController');
  Route::delete('/destroyAllByExpertId/{expert_id}', ['uses' => 'KriteriaKriteriaController@destroyAllByExpertId', 'as' => 'dKri']);
  Route::delete('/destroyAllSubByKriteriaId/{kriteria_id}', ['uses'=>'SubKriteriaSubKriteriaController@destroyAllByKriteriaId', 'as' => 'dSub']);
  Route::delete('/destroyAllPSubsByExpertId/{expert_id}', ['uses'=>'PemasokSubController@destroyAllByExpertId', 'as'=>'dPSub']);


});

app/Models/SubKriteriaSubKriteria.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class SubKriteriaSubKriteria
 * @package App\Models
 * @version October 14, 2017, 8:42 pm UTC
 *
 * @property integer sub_kriteria1_id
 * @property integer sub_kriteria2_id
 * @property integer expert_id
 * @property integer nilai
 */
class SubKriteriaSubKriteria extends Model
{
    use SoftDeletes;

    public $table = 'sub_kriteria_sub_kriterias';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'sub_kriteria1_id',
        'sub_kriteria2_id',
        'expert_id',
        'nilai',
        'kriteria_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'sub_kriteria1_id' => 'integer',
        'sub_kriteria2_id' => 'integer',
        'expert_id' => 'integer',
        'nilai' => 'float',
        'kriteria_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'sub_kriteria1_id' => 'required',
        'sub_kriteria2_id' => 'required',
        'expert_id' => 'required',
        'nilai' => 'required',
        'kriteria_id' => 'required'
    ];

    // public function kriteria(){
    //   return $this->hasManyThrough('App\Models\Kriteria', 'App\Models\Kriteria');
    // }

    public function expert()
    {
        return $this->belongsTo('App\Models\Expert', 'expert_id', 'id');
    }
}

app/Http/Controllers/SubKriteriaSubKriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSubKriteriaSubKriteriaRequest;
use App\Http\Requests\UpdateSubKriteriaSubKriteriaRequest;
use App\Repositories\SubKriteriaSubKriteriaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Models\Expert;
use App\Models\Kriteria;
use App\Models\SubKriteriaSubKriteria;
use App\Models\SubKriteria;

class SubKriteriaSubKriteriaController extends AppBaseController
{
    /** @var  SubKriteriaSubKriteriaRepository */
    private $subKriteriaSubKriteriaRepository;

    public function __construct(SubKriteriaSubKriteriaRepository $subKriteriaSubKriteriaRepo)
    {
        $this->subKriteriaSubKriteriaRepository = $subKriteriaSubKriteriaRepo;
    }

    /**
     * Display a listing of the SubKriteriaSubKriteria.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->subKriteriaSubKriteriaRepository->pushCriteria(new RequestCriteria($request));
        $subKriteriaSubKriterias = $this->subKriteriaSubKriteriaRepository->all();

        return view('sub_kriteria_sub_kriterias.index')
            ->with('subKriteriaSubKriterias', $subKriteriaSubKriterias);
    }

    /**
     * Show the form for creating a new SubKriteriaSubKriteria.
     *
     * @return Response
     */
    public function create($id)
    {
      $subKriterias = SubKriteria::all()->where('kriteria_id', '=', $id);
      $sKs = SubKriteria::all()->where('kriteria_id', '=', $id)->pluck('nama_sub_kriteria','id');
      $kriteria = Kriteria::find($id);
      $allSS = SubKriteriaSubKriteria::all()->where('kriteria_id', '=', $id);
      $expert = Expert::all();
      $e = Expert::all()->pluck('nama', 'id');
      $selectedExpert = null;
      foreach ($expert as $ex) {
        $subKriteriasCount = countTable($subKriterias->count());
        $expertInSS = $allSS->where('expert_id', '=', $ex->id);
        if($expertInSS->count() < $subKriteriasCount){
          $selectedExpert = $ex;
          break;
        }
      }
      if($selectedExpert == null){
        return view('sub_kriteria_sub_kriterias.create')->with('fullExpert', true)->with('kriteria', $kriteria)
                ->with('subKriterias', $sKs)->with('subKriteriaSubKriterias', $allSS)
                ->with('expert', $e);
      }
      $subKriteriaSubKriterias = SubKriteriaSubKriteria::all()->where('expert_id', '=', $selectedExpert->id);
      $subKriteria1 = null;
      $subKriteria2 = null;
      $ketemu = false;
      $full = countTable($subKriterias->count()) == $subKriteriaSubKriterias->count() ? true : false;
      $count = 0;
      foreach ($subKriterias as $k1) {

        $count = $subKriteriaSubKriterias->where('sub_kriteria1_id', '=', $k1->id)->count() + $subKriteriaSubKriterias->where('sub_kriteria2_id', '=', $k1->id)->count();
        if($count < $subKriterias->count()){
          foreach ($subKriterias as $k2) {
              $ada1 = $subKriteriaSubKriterias->where('sub_kriteria1_id', '=', "$k1->id")->where('sub_kriteria2_id', '=', "$k2->id")->count();
              $ada2 = $subKriteriaSubKriterias->where('sub_kriteria1_id', '=', "$k2->id")->where('sub_kriteria2_id', '=', "$k1->id")->count();
              if($ada1 == 0 && $ada2 == 0 && $k1 != $k2){
                $subKriteria1 = $k1;
                $subKriteria2 = $k2;
                $ketemu = true;
                break;
              }
          }
        }

        if($ketemu==true) break;
      }
      return view('sub_kriteria_sub_kriterias.create')
                  ->with('subKriteria1', $subKriteria1)->with('subKriteria2', $subKriteria2)
                  ->with('full', $full)->with('expert', $selectedExpert)
                  ->with('fullExpert', false)->with('kriteria',$kriteria)
                  ->with('subKriteriaSubKriterias', $allSS)
                  ->with('subKriterias', $sKs)
                  ->with('experts', $e);
    }

    /**
     * Store a newly created SubKriteriaSubKriteria in storage.
     *
     * @param CreateSubKriteriaSubKriteriaRequest $request
     *
     * @return Response
     */
    public function store(CreateSubKriteriaSubKriteriaRequest $request)
    {
        $input = $request->all();

        $subKriteriaSubKriteria = $this->subKriteriaSubKriteriaRepository->create($input);

        Flash::success('Sub Kriteria Sub Kriteria saved successfully.');

        return \App::make('redirect')->back();
        //redirect(route('subKriteriaSubKriterias.index'));
    }

    /**
     * Display the specified SubKriteriaSubKriteria.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $subKriteriaSubKriteria = $this->subKriteriaSubKriteriaRepository->findWithoutFail($id);

        if (empty($subKriteriaSubKriteria)) {
            Flash::error('Sub Kriteria Sub Kriteria not found');

            return redirect(route('subKriteriaSubKriterias.index'));
        }

        return view('sub_kriteria_sub_kriterias.show')->with('subKriteriaSubKriteria', $subKriteriaSubKriteria);
    }

    /**
     * Show the form for editing the specified SubKriteriaSubKriteria.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $subKriteriaSubKriteria = $this->subKriteriaSubKriteriaRepository->findWithoutFail($id);
        $expert = Expert::find($subKriteriaSubKriteria->expert_id);
        $subKriteria1 = SubKriteria::find($subKriteriaSubKriteria->sub_kriteria1_id);
        $subKriteria2 = SubKriteria::find($subKriteriaSubKriteria->sub_kriteria2_id);
        $kriteria   = Kriteria::find($subKriteriaSubKriteria->kriteria_id);
        if (empty($subKriteriaSubKriteria)) {
            Flash::error('Sub Kriteria Sub Kriteria not found');

            return redirect(route('subKriteriaSubKriterias.index'));
        }

        return view('sub_kriteria_sub_kriterias.edit')->with('subKriteriaSubKriteria', $subKriteriaSubKriteria)
            ->with('expert', $expert)
            ->with('subKriteria1', $subKriteria1)
            ->with('subKriteria2', $subKriteria2)
            ->with('kriteria', $kriteria);
    }

    /**
     * Update the specified SubKriteriaSubKriteria in storage.
     *
     * @param  int              $id
     * @param UpdateSubKriteriaSubKriteriaRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSubKriteriaSubKriteriaRequest $request)
    {
        $subKriteriaSubKriteria = $this->subKriteriaSubKriteriaRepository->findWithoutFail($id);

        if (empty($subKriteriaSubKriteria)) {
            Flash::error('Sub Kriteria Sub Kriteria not found');

            return redirect(route('kriterias.subKriteriaSubKriterias.create',[$id => $sId]));
        }
        $sId = $subKriteriaSubKriteria->kriteria_id;
        $subKriteriaSubKriteria = $this->subKriteriaSubKriteriaRepository->update($request->all(), $id);

        Flash::success('Sub Kriteria Sub Kriteria updated successfully.');

        return redirect(route('kriterias.subKriteriaSubKriterias.create',[$id => $sId]));
    }


    public function destroyAllByKriteriaId($kriteria_id){
      $subKriteriaSubKriteria = SubKriteriaSubKriteria::where('kriteria_id','=',$kriteria_id);
      if (empty(count($subKriteriaSubKriteria->get()))) {
          Flash::error('Sub Kriteria Sub Kriteria not found');

          return \App::make('redirect')->back();
      }

      $subKriteriaSubKriteria->delete();

      Flash::success('Sub Kriteria Sub Kriteria deleted successfully.');

      return \App::make('redirect')->back();
    }
}

resources/views/sub_kriteria_sub_kriterias/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sub Kriteria Sub Kriteria
        </h1>
        <h1 class="pull-right">
          {!! Form::open(['route' => ['dSub', $kriteria->id], 'method' => 'delete']) !!}
          {!! Form::button('Delete All', ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
          {!! Form::close() !!}
        </h1>
    </section>
    <div class="content">
      <div class="clearfix"></div>

      @include('flash::message')
      @php
        //dd($expert);
      @endphp
      <div class="clearfix"></div>
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

          @if($fullExpert)

              <div class="clearfix"></div>
              Semua Expert sudah mengisi perbandingan sub kriteria pada <b>{!! $kriteria->nama_kriteria!!}</b>!
              <div class="clearfix"></div>
          @else
            <div class="box-body">
              <br>
              {!! Form::open(['route' => ['kriterias.SubKriterias.create', $kriteria->id], 'method' => 'get']) !!}
                  {!! Form::button('Kembali', ['type' => 'submit', 'class' => 'btn btn-default']) !!}
              {!! Form::close() !!}
              <br>
                <div class="row">
                    {!! Form::open(['route' => 'subKriteriaSubKriterias.store']) !!}

                        @include('sub_kriteria_sub_kriterias.fields')

                    {!! Form::close() !!}
                </div>
            </div>
          @endif
        </div>
        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('sub_kriteria_sub_kriterias.table')
            </div>
        </div>
    </div>
@endsection

resources/views/sub_kriteria_sub_kriterias/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sub Kriteria Sub Kriteria
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($subKriteriaSubKriteria, ['route' => ['subKriteriaSubKriterias.update', $subKriteriaSubKriteria->id], 'method' => 'patch']) !!}

                        @include('sub_kriteria_sub_kriterias.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/sub_kriteria_sub_kriterias/fields.blade.php
<!-- Expert Id Field -->
<div class="form-group col-sm-12">
    <h3>Input Perbandingan Sub Kriteria oleh <b>{!! $expert->nama !!}</b> </h3>
    {!! Form::hidden('expert_id', $expert->id) !!}
</div>
<!-- Sub Kriteria1 Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('sub_kriteria1_id', 'Sub Kriteria1 Id:') !!}
    {!! Form::text('', $subKriteria1->nama_sub_kriteria, ['class' => 'form-control', 'disabled']) !!}
    {!! Form::hidden('sub_kriteria1_id', $subKriteria1->id) !!}
</div>

<!-- Nilai Field -->
<div class="form-group col-sm-3">
    {!! Form::label('nilai', 'Nilai:') !!}
    {!! Form::text('nilai', null, ['class' => 'form-control', 'autofocus']) !!}
</div>

<!-- Sub Kriteria2 Id Field -->
<div class="form-group col-sm-3">
    {!! Form::label('sub_kriteria2_id', 'Sub Kriteria2 Id:') !!}
    {!! Form::text('', $subKriteria2->nama_sub_kriteria, ['class' => 'form-control', 'disabled']) !!}
    {!! Form::hidden('sub_kriteria2_id', $subKriteria2->id) !!}
</div>


{!! Form::hidden('kriteria_id', $kriteria->id) !!}


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/sub_kriteria_sub_kriterias/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Sub Kriteria Sub Kriterias</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('subKriteriaSubKriterias.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('sub_kriteria_sub_kriterias.table')
            </div>
        </div>
    </div>
@endsection

resources/views/sub_kriteria_sub_kriterias/kriterias.blade.php
@extends('layouts.app')
{!! dd($kriterias)!!}
@section('content')
    <section class="content-header">
        <h1 class="pull-left">Kriterias</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('kriterias.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
              <table class="table table-responsive" id="kriterias-table">
                  <thead>
                      <tr>
                          <th>Nama Kriteria</th>
                          <th></th>
                          <th></th>
                      </tr>
                  </thead>
                  <tbody>
                  @foreach($kriterias as $kriteria)
                      <tr>
                          <td>{!! $kriteria->nama_kriteria !!}</td>
                          <td>
                          {!! Form::open(['route' => ['CreateSubKriteriaSubKriteria', [$expert->id, $kriteria->id]], 'method' => 'get']) !!}
                              {!! Form::button('Input Perbandingan', ['type' => 'submit', 'class' => 'btn btn-primary btn-xs']) !!}
                          {!! Form::close() !!}
                          </td>
                      </tr>
                  @endforeach
                  </tbody>
              </table>

            </div>
        </div>
    </div>
@endsection

resources/views/sub_kriteria_sub_kriterias/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sub Kriteria Sub Kriteria
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('sub_kriteria_sub_kriterias.show_fields')
                    <a href="{!! route('subKriteriaSubKriterias.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sub_kriteria_sub_kriterias/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $subKriteriaSubKriteria->id !!}</p>
</div>

<!-- Sub Kriteria1 Id Field -->
<div class="form-group">
    {!! Form::label('sub_kriteria1_id', 'Sub Kriteria1 Id:') !!}
    <p>{!! $subKriteriaSubKriteria->sub_kriteria1_id !!}</p>
</div>

<!-- Sub Kriteria2 Id Field -->
<div class="form-group">
    {!! Form::label('sub_kriteria2_id', 'Sub Kriteria2 Id:') !!}
    <p>{!! $subKriteriaSubKriteria->sub_kriteria2_id !!}</p>
</div>

<!-- Expert Id Field -->
<div class="form-group">
    {!! Form::label('expert_id', 'Expert Id:') !!}
    <p>{!! $subKriteriaSubKriteria->expert_id !!}</p>
</div>

<!-- Nilai Field -->
<div class="form-group">
    {!! Form::label('nilai', 'Nilai:') !!}
    <p>{!! $subKriteriaSubKriteria->nilai !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $subKriteriaSubKriteria->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $subKriteriaSubKriteria->updated_at !!}</p>
</div>

resources/views/sub_kriteria_sub_kriterias/table.blade.php
<table class="table table-responsive" id="subKriteriaSubKriterias-table">
    <thead>
        <tr>
        <th>#</th>
        <th>Expert</th>
        <th>Sub Kriteria 1</th>
        <th>Nilai</th>
        <th>Sub Kriteria 2</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
      @php
        $no = 1;
      @endphp
    @foreach($subKriteriaSubKriterias as $subKriteriaSubKriteria)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $subKriteriaSubKriteria->expert->nama !!}</td>
            <td>{!! $subKriterias[$subKriteriaSubKriteria->sub_kriteria1_id] !!}</td>
            <td>{!! $subKriteriaSubKriteria->nilai !!}</td>
            <td>{!! $subKriterias[$subKriteriaSubKriteria->sub_kriteria2_id] !!}</td>
            <td>
                <div class='btn-group'>
                    <a href="{!! route('subKriteriaSubKriterias.edit', [$subKriteriaSubKriteria->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                </div>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>